language: go
go:
- 1.10.x
script:
- make
deploy:
  provider: releases
  api_key:
    secure: r1e70+3OBtLeyT8kAexDLIFUZfpLzHO55/sFtIlC5XJEWytleFYCTtBgy05dRT3PpDlWb5FGoef7MAV6IK9kQ7AgaQIgS2TnfqTHqayiDSmqY8ia8zOf8Py+83p69RgLM4QWO9uFqKC2F0KyTpmH8UMCDw5dRNHlr6tmocGXvi8iJE5SIEM3YQEO98SUEvOdzNvvEyZputzoWwusOSVqZlJaJdcG9+sEpk77SRPuC3TDtQ5UiVBX8Qejf/+k499IeilZhob6WnuSegWcIWWVMwUpNSI//Mr/f2rwcltS3AJGZ5ytvE7iq2Hm9uDn+GWIyFjKFXeoZIatg23hUuVBYZJ5EuS17Hm2wcTLc3UmzIqYS2HUCOINx1/Xji6DzZDMQIRlGwZhLpTEbzDtEH3eWKSOZTQhbzunGQ5sO4MORscM78k6corsp8B+xL0gk7POLzIwdb7lRnoGhUriHhEgODm0Rdh9BWgk6PDJ77pZ4IXC0BjRRT2c6JGp191fciFQ46dkiqc4EPyakM785cWpK/nvheotLXj+57EcyZ4puqaVhZ8csfsernGt4tWoRNxmeVleBjVQDg3I4znA0ZroLnuhXJ9xoYsaTZbQcECNX9KLdVO700QKwrNRLW2fjnbZmeMs8d+Fk/0RB+AF2rpAtLrAy5bw5rVczq2I35fHxWM=
  skip_cleanup: true
  file: build/make-jks-linux-x64
  on:
    tags: true
    repo: bsycorp/make-jks